# Generated by Django 4.1.7 on 2023-02-28 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DentistDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=100)),
                ('edication_grade', models.CharField(choices=[('doctor', 'doctor'), ('magister', 'magister')], default=('doctor', 'doctor'), max_length=8)),
                ('experience', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('visit_date', models.DateTimeField()),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='denta.dentistdoctor')),
            ],
        ),
    ]
